Project partner logos
ProvideQ/ProvideQ pull request #12
Opened 2023-03-07 11:19 UTC by Elscrux

2023-04-02 17:46 UTC, Elscrux commented
@schweikart Can we merge this?

2023-04-07 09:58 UTC, schweikart commented
The suggested layout works but I think we can improve the layout a bit. I think we should re-organize the legal links (imprint + privacy) and we should maybe make the project partner logos less prominent.

This is the current layout:

![Screenshot from 2023-04-07 10 54 44](https://user-images.githubusercontent.com/60352933/230577813-456bab35-5dae-4d16-956c-f7d95be14ac3.png)

Here is my take on the design (pushed to branch `project-partner-logos-alternate-layout`):

![Screenshot from 2023-04-07 11 51 32](https://user-images.githubusercontent.com/60352933/230588078-ee1ee7ba-ef5d-4ee7-b7a8-bfef1e8376f7.png)

Also, the 4flow logo seems to be have a different tone of white for its background. Do you think we can get a transparent version of their logo?

![Screenshot from 2023-04-07 11 55 34](https://user-images.githubusercontent.com/60352933/230589105-429c1776-7d6d-40c8-b551-62e41b62b78a.png)

2023-04-07 10:02 UTC, schweikart requested changes

2023-04-07 10:02 UTC, schweikart commented on src/pages/index.tsx
> +import { URL } from "next/dist/compiled/@edge-runtime/primitives/url";
unnecessary import

2023-04-07 10:02 UTC, schweikart commented on public/4flow.svg
as mentioned in my comment: can we get a transparent version of this logo?

2023-04-07 10:02 UTC, schweikart commented on src/pages/index.tsx
>            <VStack>
the `VStack` wrapper can be omitted for these single-element nodes

2023-04-09 17:31 UTC, Elscrux commented
Seeing as you've done most of the work fixing these issues I think we can switch to that branch instead. I uploaded the transparent 4flow logo so now hopefully everything is in place to be merged.

2023-04-09 17:57 UTC, Elscrux commented
I've merged the alternate style branch and included the last fixes

2023-04-09 19:53 UTC, schweikart approved these changes

2023-04-09 19:54 UTC, schweikart commented
perfect, thanks :raised_hands:

2023-04-09 19:55 UTC, merged