Meta solver settings
ProvideQ/ProvideQ pull request #15
Opened 2023-04-24 21:41 UTC by Elscrux

Based on feature-model/anomaly, sorry I needed changes from there to implement this without major conflicts.

2023-05-02 18:10 UTC, schweikart requested changes

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SolverPicker.tsx
> +            solveRequest.requestedSolverId = undefined;
updating state objects directly should be avoided and often results in state bugs. Please use the setter instead: https://react.dev/learn/updating-objects-in-state#treat-state-as-read-only

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SolverPicker.tsx
> +    problemType?: string;
Is this the name of the solver? What do you mean with "only needed internally"? Why is this optional and what happens if you omit it?

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SolverPicker.tsx
> +            {subRoutines == undefined || subRoutines.length == 0
is the `length == 0` check necessary?

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SolverPicker.tsx
> +                                    solveRequest.requestedMetaSolverSettings = settings;
as mentioned above, please avoid modifying state directly

(in this case: Shouldn't propagating the state to the parent in the line below also update the `solveRequest`?)

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SettingsView.tsx
> +}
please move these types away from the `components` folder, maybe to a new module in the `api` folder

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/ProgressHandler.tsx
> +                                          solveRequest.requestedSubSolveRequests = solverChoice.requestedSubSolveRequests;
please do not modify state objects directly! use `setSolveRequest` instead

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SettingsView.tsx
> +                                            range.value = v
do not update state directly, use `setSettings()` instead

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SettingsView.tsx
> +                                                        checkbox.state = e.target.checked;
do not update state directly, use `setSettings()` instead

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SettingsView.tsx
> +                                                        text.text = e.target.value;
do not update state directly, use `setSettings()` instead

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SettingsView.tsx
> +                                            select.selectedOption = e.target.value;
do not update state directly, use `setSettings()` instead

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SolverPicker.tsx
>              solveRequest.requestedSolverId = solver.id;
do not update state directly, use `setSolveRequest()` instead

2023-05-02 18:10 UTC, schweikart commented on src/components/solvers/SolverPicker.tsx
> +                                solveRequest.requestedSubSolveRequests.set(def.type, subSolveRequest);
do not update state directly, use `setSolveRequest()` instead

2023-05-02 18:19 UTC, schweikart commented
Please rebase onto the target branch instead of merging. When merging, a lot of unnecessary commits will be generated and diff tool's will show me the merged changes for this branch when I try to review them.

2023-05-03 07:38 UTC, Elscrux commented on src/components/solvers/SolverPicker.tsx
> +                                solveRequest.requestedSubSolveRequests.set(def.type, subSolveRequest);
The Sub-SolveRequest needs to be added to the map here.
Do you want me to update the state in a duplicate object and then set that via setter?

2023-05-03 07:53 UTC, Elscrux commented on src/components/solvers/SolverPicker.tsx
> +                                    solveRequest.requestedMetaSolverSettings = settings;
No, the parent doesn't necessarily update the solveRequest. See setSolveRequest at the end of SolverPicker.
It's more of an onSolverRequestChanged event.

2023-05-03 08:03 UTC, Elscrux commented on src/components/solvers/SolverPicker.tsx
> +            {subRoutines == undefined || subRoutines.length == 0
Yes, otherwise an empty box would be displayed when the array is set to []. For example in line [] iirc.

2023-05-03 08:12 UTC, Elscrux commented on src/components/solvers/SettingsView.tsx
> +                                            range.value = v
For these settings events we have to create a new array, and replace one element in it. Seems like a strange way of doing it, but ok.
Do you know a good way of dealing with this here?

2023-05-03 08:18 UTC, Elscrux commented
> I have a request for dealing with changes in the upstream branch: Please rebase onto the target branch instead of merging. When merging, a lot of unnecessary commits will be generated and diff tool's will show me the merged changes for this branch when I try to review them.

Sorry seems, like rebasing went wrong somehow. I'll fix it

2023-05-03 08:30 UTC, Elscrux commented on src/components/solvers/SolverPicker.tsx
> +    problemType?: string;
Internally means that only the nested calls in the SolverPicker uses it to display additional information for Subroutines.
So when you use the SolverPicker externally, like in ProgressHandler, you shouldn't need to specify it.

2023-06-07 08:59 UTC, schweikart approved these changes

2023-06-07 08:59 UTC, merged