Remove logical expression parsing
ProvideQ/ProvideQ pull request #38
Opened 2023-11-02 18:31 UTC by Elscrux

Fixing the bug that caused formulas like `not (something)` to be displayed in correctly.
The dimacs parser didn't support this change out of the box, so I removed it as we no longer need it.

2023-11-22 08:14 UTC, schweikart requested changes
works as exepected! here are a couple of minor comments

2023-11-22 08:14 UTC, schweikart commented on __tests__/converter/dimacs/DimacsLogicalExpression.spec.ts
> +  /*each([
Please don't keep dead code, we can look this up in Git in case we need it again

2023-11-22 08:14 UTC, schweikart commented on src/pages/solve/SAT.tsx
>              setErrorString("");
As we're changing this code anyways: please use `null` to indicate the absence of values

2023-11-22 08:14 UTC, schweikart commented on src/converter/dimacs/LogicalExpressionParser.ts
>     * @returns {string} formula in dimacs sat format of the input
Is this `@returns` still correct? the type seems wrong and if i see this correctly, the meaning of the return value has changed, too

2023-11-22 08:14 UTC, schweikart commented on src/converter/dimacs/LogicalExpressionParser.ts
>  export class LogicalExpressionParser {
Since this is not really a parser any more, maybe rename this class?

2024-01-09 10:06 UTC, schweikart requested changes

2024-01-09 10:06 UTC, schweikart commented on src/pages/solve/SAT.tsx
>              setErrorString("");
I see now that this has been unclear. It's good that `LogicalExpressionValidator` returns an empty array if there are no errors. But `setErrorString("")` doesn't make sense to me as `null` denotes the absence of an error string whereas `""` denotes the presence of an empty error string.

Please excuse my lack of clarity. Make the validator return an empty array again and use `setErrorString(null)` if there are no errors.

2024-01-14 12:18 UTC, Elscrux commented
@schweikart All should be ready now :)

2024-01-22 15:04 UTC, schweikart approved these changes
Perfect, thanks!

2024-01-22 15:26 UTC, schweikart commented
Rebased onto reformatted code

2024-01-22 15:27 UTC, merged